export const getContantFields = (
  tg,
  position,
  stage,
  amount,
  dateFunding,
  aboutFounder,
  whereFrom,
  ld,
  cb,
  problem,
  email,
  whereMoneyFounder,
  whereMoneyCompany,
  inst,
  whereInfo
) => {
  return [
    {
      field_id: 697949,
      field_name: "Телефон",
      field_code: "PHONE",
      field_type: "multitext",
      values: [{ value: tg }],
    },
    {
      field_id: 697947,
      field_name: "Должность",
      field_code: "POSITION",
      field_type: "text",
      values: [{ value: position }],
    },
    {
      field_id: 979911,
      field_name: "Откуда деньги у фаундера?",
      field_code: null,
      field_type: "text",
      values: [{ value: whereMoneyFounder }],
    },
    {
      field_id: 979913,
      field_name: "Откуда деньги компании?",
      field_code: null,
      field_type: "text",
      values: [{ value: whereMoneyCompany }],
    },
    {
      field_id: 980233,
      field_name: "откуда фаундер",
      field_code: null,
      field_type: "text",
      values: [{ value: whereFrom }],
    },
    {
      field_id: 980235,
      field_name: "рынок продукта",
      field_code: null,
      field_type: "text",
      values: [{ value: whereFrom }],
    },
    {
      field_id: 983293,
      field_name: "CrunchBase",
      field_code: null,
      field_type: "url",
      values: [{ value: cb }],
    },
    {
      field_id: 986325,
      field_name: "LD",
      field_code: null,
      field_type: "text",
      values: [{ value: ld }],
    },
    {
      field_id: 983301,
      field_name: "about founder",
      field_code: null,
      field_type: "text",
      values: [{ value: aboutFounder }],
    },
    {
      field_id: 983303,
      field_name: "TG",
      field_code: null,
      field_type: "text",
      values: [{ value: tg }],
    },
    {
      field_id: 983311,
      field_name: "stage",
      field_code: null,
      field_type: "text",
      values: [{ value: stage }],
    },
    {
      field_id: 983313,
      field_name: "date funding",
      field_code: null,
      field_type: "text",
      values: [{ value: dateFunding }],
    },
    {
      field_id: 983315,
      field_name: "investor name",
      field_code: null,
      field_type: "text",
      values: [{ value: tg }],
    },
    {
      field_id: 983445,
      field_name: "total funding amount",
      field_code: null,
      field_type: "text",
      values: [{ value: amount }],
    },
    {
      field_id: 697951,
      field_name: "Email",
      field_code: "EMAIL",
      field_type: "multitext",
      values: [{ value: email }],
    },
    {
      field_id: 983299,
      field_name: "problem",
      field_code: null,
      field_type: "text",
      values: [{ value: problem }],
    },
    {
      field_id: 985809,
      field_name: "откуда информация про проблему",
      field_code: null,
      field_type: "text",
      values: [{ value: whereInfo }],
    },
    {
      field_id: 985893,
      field_name: "INST",
      field_code: null,
      field_type: "url",
      values: [{ value: inst }],
    },
  ];
};
